# Generated by Django 3.1.7 on 2021-08-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=120)),
                ('apikey', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('IDa', models.CharField(max_length=120)),
                ('urlCam', models.CharField(max_length=120)),
                ('TSDid', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('---', '---------'), ('music', 'music '), ('science', 'science '), ('social science', 'social science '), ('math', 'math '), ('tecnology', 'tecnology '), ('physics', 'physics '), ('chemistry', 'chemistry '), ('Crafts', 'Crafts '), ('Art history', 'Art history ')], default='1', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('uniqueId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TSD_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printerManagerApp.project')),
            ],
        ),
    ]
