# Generated by Django 3.1.7 on 2021-09-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printerManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='urlCam',
        ),
    ]
