# Generated by Django 3.0.5 on 2021-09-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerManagerApp', '0002_remove_printer_urlcam'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='urlCam',
            field=models.CharField(default='caca', max_length=120),
            preserve_default=False,
        ),
    ]
