# Generated by Django 3.1.7 on 2021-12-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printerManagerApp', '0003_printer_urlcam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TSD_url',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='TSDid',
        ),
    ]
