version: '3.7'

services:
  app:
    build:
      context: .   
    network_mode: host
    volumes: 
      - static_data:/vol/web   
      - media_data:/vol/web   
    environment: 
      - DEBUG=0
    restart: always
   
  proxy:
    build: 
      context: ./proxy
    network_mode: host  
    volumes: 
      - static_data:/vol
      - media_data:/vol
    depends_on: 
      - app
    restart: always

volumes: 
  static_data:
