version: '3.3'

services:
  app:
    build:
      context: .
    network_mode: host
    volumes:
      - static_data:/vol/web/static
      - media_data:/vol/web/media
    environment:
      - DEBUG=0
    restart: always

  proxy:
    build:
      context: ./proxy
    network_mode: host
    volumes:
      - static_data:/vol/static
      - media_data:/vol/media
    depends_on:
      - app
    restart: always

volumes:
  static_data: null
  media_data: null
